/**创建数据库**/  
CREATE DATABASE IF NOT EXISTS DB_YUNDUAN_PAY;  
USE DB_YUNDUAN_PAY;  
/**--修改默认字符集**/  
ALTER DATABASE DEFAULT CHARSET=UTF8;  

/**创建用户并赋予用户DB_YUNDUAN_PAY数据库所有权限**/
GRANT ALL PRIVILEGES ON DB_YUNDUAN_PAY.* TO DB_YUNDUAN_PAY@"%" IDENTIFIED BY "DB_YUNDUAN_PAY";
GRANT ALL PRIVILEGES ON DB_YUNDUAN_PAY.* TO DB_YUNDUAN_PAY@"localhost" IDENTIFIED BY "DB_YUNDUAN_PAY";
GRANT ALL PRIVILEGES ON DB_YUNDUAN_PAY.* TO DB_YUNDUAN_PAY@"127.0.0.1" IDENTIFIED BY "DB_YUNDUAN_PAY";
FLUSH PRIVILEGES;

/**创建日志数据库**/  
CREATE DATABASE IF NOT EXISTS DB_YUNDUAN_PAY_LOG;
USE DB_YUNDUAN_PAY_LOG;
/**--修改默认字符集**/  
ALTER DATABASE DEFAULT CHARSET=UTF8;

/**创建用户并赋予用户DB_YUNDUAN_PAY_LOG数据库所有权限**/
GRANT ALL PRIVILEGES ON DB_YUNDUAN_PAY_LOG.* TO DB_YUNDUAN_PAY_LOG@"%" IDENTIFIED BY "DB_YUNDUAN_PAY_LOG";
GRANT ALL PRIVILEGES ON DB_YUNDUAN_PAY_LOG.* TO DB_YUNDUAN_PAY_LOG@"localhost" IDENTIFIED BY "DB_YUNDUAN_PAY_LOG";
GRANT ALL PRIVILEGES ON DB_YUNDUAN_PAY_LOG.* TO DB_YUNDUAN_PAY_LOG@"127.0.0.1" IDENTIFIED BY "DB_YUNDUAN_PAY_LOG";
FLUSH PRIVILEGES;