DROP TABLE IF EXISTS FS_T_BIDDER;
CREATE TABLE FS_T_BIDDER
(
   ID                   VARCHAR(32) NOT NULL COMMENT '主键ID',
   V_CA_USER_ID         VARCHAR(32) COMMENT 'CA用户表ID',
   V_JSON_OBJ           LONGTEXT COMMENT '其他扩展信息',
   V_BUS_FILE_ID        VARCHAR(32) COMMENT '营业执照附件ID',
   V_QUAL_FILE_ID       VARCHAR(32) COMMENT '其他资质附件ID',
   N_CREATE_TIME        BIGINT COMMENT '创建时间',
   N_UPDATE_TIME        BIGINT COMMENT '修改时间',
   V_CREATE_USER        VARCHAR(32) COMMENT '创建人员',
   V_UPDATE_USER        VARCHAR(32) COMMENT '修改人员',
   PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='投保人扩展信息';

DROP TABLE IF EXISTS FS_T_FINANCIAL;
CREATE TABLE FS_T_FINANCIAL
(
   ID                   VARCHAR(32) NOT NULL COMMENT 'ID',
   V_CA_USER_ID         VARCHAR(32) COMMENT 'CA用户信息表的ID',
   V_AREA_CODE          VARCHAR(10) COMMENT '行政区域编码',
   V_ZIP_CODE           VARCHAR(6) COMMENT '邮编',
   V_URL                VARCHAR(255) COMMENT '保函验证网站',
   V_EMAIL              VARCHAR(255) COMMENT '邮箱',
   V_TEL                VARCHAR(20) COMMENT '电话',
   V_FAX                VARCHAR(20) COMMENT '传真',
   V_PRAISE_RATE        FLOAT COMMENT '好评率',
   V_INTRODUCE          LONGTEXT COMMENT '公司介绍',
   V_COM_FILE_ID        VARCHAR(32) COMMENT '公司图片附件',
   V_QUAL_FILE_ID       VARCHAR(32) COMMENT '营业执照附件',
   V_JSON_OBJ           LONGTEXT COMMENT '其他扩展信息',
   N_CREATE_TIME        BIGINT COMMENT '创建时间',
   N_UPDATE_TIME        BIGINT COMMENT '修改时间',
   V_CREATE_USER        VARCHAR(32) COMMENT '创建人员',
   V_UPDATE_USER        VARCHAR(32) COMMENT '修改人员',
   PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='金融机构扩展信息表';

DROP TABLE IF EXISTS FS_T_LEFFER;
CREATE TABLE FS_T_LEFFER
(
   ID                   VARCHAR(32) NOT NULL COMMENT '主键ID',
   V_NO                 VARCHAR(100) COMMENT '保函编号',
   V_PROJECT_TENDER_CODE VARCHAR(100) COMMENT '招标项目编号',
   V_PROJECT_TENDER_NAME VARCHAR(300) COMMENT '招标项目名称',
   V_NOTICE_URL         VARCHAR(255) COMMENT '招标公告URL',
   V_BIDDER_ID          VARCHAR(32) COMMENT '投保人ID',
   V_FINANCIAL_ID       VARCHAR(32) COMMENT '金融机构ID',
   N_LEFFER_STATUS      INT(10) COMMENT '类型，0保函,1取消保函',
   N_APPLY_STATUS		INT(10) COMMENT '申请状态0:正常,1:取消',
   N_SIGN_STATUS        INT(10) COMMENT '签约状态,0：未签约,1：已签约',
   N_AUDIT_STATUS       INT(10) COMMENT '保函状态,0：未验证,1：审核通过,2：审核不通过',
   V_LEFFER_FILE_ID     VARCHAR(32) COMMENT '保函文件ID',
   V_JSON_OBJ           LONGTEXT COMMENT '其他扩展信息',
   N_CREATE_TIME        BIGINT COMMENT '创建时间',
   N_UPDATE_TIME        BIGINT COMMENT '修改时间',
   V_CREATE_USER        VARCHAR(32) COMMENT '创建人员',
   V_UPDATE_USER        VARCHAR(32) COMMENT '修改人员',
   PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='保函信息';

DROP TABLE IF EXISTS FS_T_ANNUAL_USER;
CREATE TABLE `FS_T_ANNUAL_USER` (
  `ID` varchar(32) NOT NULL COMMENT '主键',
  `V_FINANCIAL_ID` varchar(32) DEFAULT NULL COMMENT '金融企业ID',
  `V_USER_NAME` varchar(200) DEFAULT NULL COMMENT '年度用户名称',
  `V_SOCIALCREDIT_NO` varchar(50) DEFAULT NULL COMMENT '社会统一信用代码',
  `V_VALIDITY_START_TIME` varchar(20) DEFAULT NULL COMMENT '有效期开始时间',
  `V_VALIDITY_END_TIME` varchar(20) DEFAULT NULL COMMENT '有效期结束时间',
  `V_JSON` longtext COMMENT '其他扩展信息',
  `N_CREATE_TIME` bigint(20) DEFAULT NULL COMMENT '创建时间',
  `N_UPDATE_TIME` bigint(20) DEFAULT NULL COMMENT '更新时间',
  `V_CREATE_USER` varchar(32) DEFAULT NULL COMMENT '创建人员',
  `V_UPDATE_USER` varchar(32) DEFAULT NULL COMMENT '修改人员',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='年度用户信息表';

DROP TABLE IF EXISTS FS_T_PUSH_LOG;
CREATE TABLE `FS_T_PUSH_LOG` (
  `ID` varchar(50) NOT NULL COMMENT 'ID',
  `V_NAME` varchar(50) DEFAULT NULL COMMENT '推送接口名称',
  `V_CALL_METHOD` varchar(100) DEFAULT NULL COMMENT '请求方法',
  `V_CALL_METHOD_DESC` varchar(100) DEFAULT NULL COMMENT '请求方法描述',
  `V_CALL_TIME` varchar(20) DEFAULT NULL COMMENT '请求时间',
  `V_CALL_PARAMS` text COMMENT '请求参数',
  `N_SUCCESS` tinyint(1) DEFAULT NULL COMMENT '执行结果，1正常，0异常',
  `V_RETURN` longtext COMMENT '返回值',
  `V_RETURN_TIME` varchar(20) DEFAULT NULL COMMENT '返回时间',
  `N_TIME_CONSUM` int(11) DEFAULT NULL COMMENT '耗费时间',
  `V_ERROR` longtext COMMENT '异常内容',
  `V_JSON` longtext COMMENT '其他扩展信息',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='接口推送日志';

DROP TABLE IF EXISTS `FS_T_LEFFER_EXT`;
CREATE TABLE `FS_T_LEFFER_EXT` (
  `ID` varchar(50) NOT NULL COMMENT '保函表FS_T_LEFFER 的ID',
  `N_SYNC_WECHAT_TIME` bigint(20) DEFAULT NULL COMMENT '微信端同步时间',
  `V_LETTER_JSON` longtext COMMENT '保函扩展信息',
  PRIMARY KEY (`ID`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='保函扩展表';

DROP TABLE IF EXISTS FS_T_PUSH_LOG;
CREATE TABLE `t_sys_product_tab` (
  `ID` varchar(32) NOT NULL COMMENT '金融产品ID',
  `PRODUCT_NAME` varchar(255) DEFAULT NULL COMMENT '金融产品名称',
  `PRODUCT_TEL` varchar(30) DEFAULT NULL COMMENT '联系电话',
  `PRODUCT_SEQ` varchar(10) DEFAULT NULL COMMENT '金融产品显示顺序',
  `IS_SHOW_HEAD` varchar(1) DEFAULT NULL COMMENT '是否在头部显示',
  `PRODUCT_DESC` varchar(1000) DEFAULT NULL COMMENT '金融产品介绍',
  `CREATE_TIME` varchar(50) DEFAULT NULL COMMENT '创建时间',
  `CREATE_USER` varchar(32) DEFAULT NULL COMMENT '创建人',
  `UPDATE_TIME` varchar(50) DEFAULT NULL COMMENT '修改时间',
  `UPDATE_USER` varchar(32) DEFAULT NULL COMMENT '修改人',
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='系统金融产品表'

