DROP TABLE IF EXISTS  T_ATTACH_TYPE_INFO;
DROP TABLE IF EXISTS  T_ATTACH_TYPE_ROLE;
DROP TABLE IF EXISTS  T_ATTACH_FILE_INFO;
DROP TABLE IF EXISTS  T_ATTACH_FILE_REFERENCE;

/************************附件分类信息表************************/   
CREATE TABLE T_ATTACH_TYPE_INFO (
  ATTACH_TYPE_ID VARCHAR(32) NOT NULL COMMENT '主键',
  V_TYPENAME VARCHAR(300) NOT NULL COMMENT '类型名称',
  V_SAVEPATH VARCHAR(255) NOT NULL COMMENT '文件保存跟路径(绝对路径)',
  N_MAXSIZE INT(11) NOT NULL COMMENT '单个文件允许的最大SIZE,单位KB',
  V_FILETYPE_EXTS VARCHAR(300) DEFAULT NULL COMMENT '允许的文件扩展名,例如:GIF,多个扩展名使用|分割',
  N_MINCOUNT INT(11) NOT NULL COMMENT '最小必须有几个文件,-1表示不限制',
  N_MAXCOUNT INT(11) NOT NULL COMMENT '最大允许有几个文件,-1表示不限制,该值如果不为-1时,必须大于MIN_COUNT',
  N_MAXWIDTH INT(11) NOT NULL COMMENT '图片文件的允许宽度,-1表示不限制,单位PX',
  N_MAXHEIGHT INT(11) NOT NULL COMMENT '图片文件的允许高度,-1表示不限制,单位PX',
  V_THMNORM VARCHAR(300) DEFAULT NULL COMMENT '图片的缩略图尺寸[WIDTH,HEIGHT例如:200,300],多个尺寸用|分割,如:80,60|120,80|200,300',
  N_ISPUREIMAGE INT(4) NOT NULL COMMENT '是否为纯图片',
  V_TYPEDESC VARCHAR(600) DEFAULT NULL COMMENT '类型描述',
  PRIMARY KEY (ATTACH_TYPE_ID)
); 
/**增加表注释**/    
ALTER TABLE T_ATTACH_TYPE_INFO COMMENT = '附件分类信息表';

/************************角色附件分类表************************/   
CREATE TABLE T_ATTACH_TYPE_ROLE(
  ROLE_ID VARCHAR(32) NOT NULL COMMENT '角色ID',
  ATTACH_TYPE_ID VARCHAR(32) NOT NULL COMMENT '附件分类ID',
  N_SIZE int(11) NOT NULL COMMENT '空间大小,单位MB',
  PRIMARY KEY (ROLE_ID,ATTACH_TYPE_ID)
);
/**增加表注释**/    
ALTER TABLE T_ATTACH_TYPE_ROLE COMMENT = '角色附件分类表';

/************************附件文件信息表************************/  
CREATE TABLE T_ATTACH_FILE_INFO (
  ATTACH_ID varchar(32) NOT NULL COMMENT '文件ID',
  ATTACH_TYPE_ID varchar(32) NOT NULL COMMENT '所属分类ID',
  V_NAME varchar(255) NOT NULL COMMENT '文件名称',
  V_REAL_PATH varchar(255) DEFAULT NULL COMMENT '文件实际保存路径,此为相对路径,相对于分类的路径',
  N_SIZE int(11) DEFAULT NULL COMMENT '文件大小,单位MB',
  V_PARENT_ID varchar(32) DEFAULT NULL COMMENT '文件所属虚拟目录ID',
  V_EXTENSION varchar(50) DEFAULT NULL COMMENT '文件扩展名',
  V_MIME_TYPE varchar(200) DEFAULT NULL COMMENT '附件的MIME类型',
  N_IS_IMAGE int(4) NOT NULL COMMENT '是否为图片0:否,1:是',
  N_IMAGE_WIDTH int(11) DEFAULT NULL COMMENT '图片文件实际宽度,单位PX',
  N_IMAGE_HEIGHT int(11) DEFAULT NULL COMMENT '图片文件实际高度,单位PX',
  V_MD5 varchar(100) DEFAULT NULL COMMENT '文件的MD5值',
  V_USER_ID varchar(32) NOT NULL COMMENT '创建的用户ID',
  V_SPECIFICATIONS varchar(50) DEFAULT NULL COMMENT '缩略图规格,格式为WIDTH*HEIGHT,例如:1204*768',
  V_ORIGINAL_ID varchar(32) DEFAULT NULL COMMENT '源图文件ID,缩略图对应的源图文件ID',
  D_CREATE_TIME datetime NOT NULL COMMENT '创建时间',
  D_UPDATE_TIME timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  V_ATTACH_DESC varchar(900) DEFAULT NULL COMMENT '文件描述',
  N_IS_DIR int(4) NOT NULL COMMENT '是否为目录,0为否,1为是',
  N_IS_THUMBNAIL int(4) NOT NULL COMMENT '是否为缩略图,0为否,1为是',
  V_COMPANY_ID varchar(32) DEFAULT NULL COMMENT '公司主键',
  PRIMARY KEY (ATTACH_ID)
);
/**增加表注释**/    
ALTER TABLE T_ATTACH_FILE_INFO COMMENT = '附件文件信息表';

/************************附件引用组表************************/ 
CREATE TABLE T_ATTACH_FILE_REFERENCE (
  REFERENCE_ID varchar(32) NOT NULL COMMENT '引用组ID',
  ATTACH_ID varchar(32) NOT NULL COMMENT '附件ID',
  USER_ID varchar(32) NOT NULL COMMENT '用户ID',
  N_COVER int(4) DEFAULT NULL COMMENT '是否为附件所属附件组的封面 0:否,1:是',
  PRIMARY KEY (REFERENCE_ID,ATTACH_ID)
);
/**增加表注释**/    
ALTER TABLE T_ATTACH_FILE_REFERENCE COMMENT = '附件引用组表';